#spring配置
spring:
  application:
    #应用名称(服务提供者)
    name: producer-service

#服务器配置
server:
  #端口
  port: 8001
  #显示名称
  display-name: producer-service1

#服务器发现注册配置
eureka:
  client:
    serviceUrl:
      #配置服务中心(可配置多个,用逗号隔开)
      defaultZone: http://localhost:9001/eureka